### ISSUE TITLE
Multiple Instruments doesn't work?

### ISSUE THREAD

**Issue by efloehr** [kroger/pyknon#12]
I am trying to make a multi-track MIDI file using a different instrument per track using the following code:
```
midi = Midi(2, tempo=100, instrument=[5,117])
midi.seq_notes(obs_notes, track=0)
midi.seq_notes(day_beat, track=1)
midi.write("temps.mid")
```
Both tracks play instrument 117, instead of track 0 playing instrument 5. Is this expected? Is my code correct? Or is this an issue? Thanks so much!

**Comment by kroger** [comment]
Hi,

It’s a bug; I’ll try to fix it.

**Comment by Robin-Andrews** [comment]
I've just noticed this myself. Would be great to get it fixed so I can add some percussion to my tracks. Is there another way around it in the meantime? For example, can you merge Midi files somehow?

**Comment by kroger** [comment]
The best way to merge midi files is to import them in some Midi sequencer.

**Comment by Robin-Andrews** [comment]
Hi Pedro,
 
Thanks for your response.
 
I can see that using a midi sequencer would work, but my interest is really in "coding music," so using a sequencer is not ideal.
 
Do you think the bug would be hard to fix? I've looked at the code with my amateur eye, and I'm guessing the problem might be in this section of genmidi.py:
 
class Midi(object):
    def __init__(self, number_tracks=1, tempo=60, instrument=0):
        """
        instrument: can be an integer or a list
        """
        self.number_tracks = number_tracks
        self.midi_data = MIDIFile(number_tracks)
        for track in range(number_tracks):
            self.midi_data.addTrackName(track, 0, "Track {0}".format(track))
            self.midi_data.addTempo(track, 0, tempo)
            instr = instrument[track] if isinstance(instrument, list) else instrument
            self.midi_data.addProgramChange(track, 0, 0, instr)

It would be great to have the functionality of creating multiple tracks with different instruments available.
 
Kind regards,
 
Robin.
 
Date: Wed, 30 Sep 2015 16:06:31 -0700

**Comment by kroger** [comment]
It should be working now. Thanks for reporting!

**Comment by kroger** [comment]
@Robin-Andrews 

Now you can specify the channel of a sequence of notes. So to use percussion, add the channel 9 (that will correspond to channel 10 in the MIDI file). See the file demo_tracks.py:

```python
n1 = NoteSeq("C4 D E F")
n2 = NoteSeq("C8 C G, G C' C G, G")

m2 = Midi(2, tempo=123, channel=[0, 9], instrument=[20, 40])
m2.seq_notes(n1, track=0, channel=0)
m2.seq_notes(n2, track=1, channel=9)
m2.write("percussion.mid")
```

**Comment by Robin-Andrews** [comment]
Very cool! Thank you.
 
Date: Sun, 4 Oct 2015 11:16:04 -0700
