### ISSUE TITLE
Add abc notation

### ISSUE THREAD

**Issue by mzdaniel** [kroger/pyknon#15]
Thank you for creating this great package! 

I did some experiments with the current notation for creating music. It works well, though it doesn't seem very intuitive as the note octave is dependent on previous modifiers. 

Is the abc notation within the scope of this package?   (maybe adding it as an alternative notation?)

**Comment by kroger** [comment]
Hi,

Unfortunately, ABC is not in the scope of this package.

Cheers,

Pedro

**Comment by mzdaniel** [comment]
I see. I'll work around the issue with subprocess to abc2midi for score writing, and use pyknon for more responsive interaction. Thank you again for making pyknon posible!
