### ISSUE TITLE
Playing on the fly

### ISSUE THREAD

**Issue by anirudt** [kroger/pyknon#16]
Hi,

I am using Pyknon for a project, where I don't want to waste time with I/O, and hence do not want to write the Midi data into a file before using Pygame to play it. Is there any way for Pyknon to play the Midi object directly?

This is also a consideration because I plan to do this repetitively. Thanks for your reply.

**Comment by kroger** [comment]
Hi,

Unfortunately, no, it can only generate the MIDI file.

**Comment by anirudt** [comment]
I see.

I do not want to waste time on I/O, and hence, on writing to files. Can I be able to generate a taw MIDI string, which I can then send using a pipe to a reader?
