### ISSUE TITLE
Is it possible to harmonize a melody generated from a sequence of numbers?

### ISSUE THREAD

**Issue by kwailamchan** [kroger/pyknon#21]
I found that `c.harmonize()` returns the chords from a given note.

My question is if there is a way to generate chords to harmonize a given sequence of notes (melody) automatically in Pyknon?

For instance, a sequence of Fibonacci as a melody, looking for a function to automatically harmonize it, so that the pieces sound more beautiful?

Thanks.

**Comment by kroger** [comment]
Hi,

Unfortunately that's not possible with Pyknon.
