### ISSUE TITLE
MIDI with octaves not working?

### ISSUE THREAD

**Issue by fosslinux** [kroger/pyknon#23]
MIDI with octave specification (or maybe NoteSeq itself) or something else is broken.

For example, using the demo in the README creates a midi file that plays back with all notes in octave 4, whereas I would expect to hear the F# in octave 8.

Am I missing something, or is it truly broken?

**Comment by kroger** [comment]
Hi,

The number in the shorthand notation refers to the duration, in this case a 1/8th note. In the shorthand notation the octave is assigned by using single quotes. This is similar to the notation used by LilyPond. My book, Music for Geeks and Nerds has more information on how to use pyknon:

https://pedrokroger.net/mfgan/

Thanks!

**Comment by fosslinux** [comment]
OH! Thank you very much!
