### ISSUE TITLE
No longer available for install with pip?

### ISSUE THREAD

**Issue by benserrette** [kroger/pyknon#25]
Doing `pip install pyknon` results in the following error:

```requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/pyknon/```

**Comment by kroger** [comment]
pyknon is not available on pyPI anymore, I suggest you install it directly from the git repository:

    pip install git+https://github.com/kroger/pyknon.git

**Comment by JohnTravolski** [comment]
> pyknon is not available on pyPI anymore, I suggest you install it directly from the git repository:
> 
> ```
> pip install git+https://github.com/kroger/pyknon.git
> ```

Why is this the case? Is there any intention on making it available with pip in the future? This is an inconvenient way to obtain it.
